
services:
  cetolhlcs-ros2-node:
    build:
      context: .
      dockerfile: dockerfile.CETOHLCS-ros2-pi
    container_name: cetolhlcs-ros2-node
    network_mode: host
    privileged: false
    volumes:
      - ./../ros2:/ros2
      - /sys:/sys 
    environment:
      - ROS_DOMAIN_ID=0
    command: >
          bash -c "source /opt/ros/humble/setup.bash &&
           cd /ros2 &&
           exec tail -f /dev/null"
    restart: unless-stopped
